DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'dental_app') THEN
    CREATE ROLE dental_app LOGIN PASSWORD 'dental_app_password' NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE;
  END IF;
END
$$;

GRANT CONNECT ON DATABASE dental_clinic_db TO dental_app;
GRANT USAGE ON SCHEMA public TO dental_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO dental_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO dental_app;
ALTER DEFAULT PRIVILEGES FOR ROLE dental_user IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO dental_app;
ALTER DEFAULT PRIVILEGES FOR ROLE dental_user IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO dental_app;
