"""add end_date to payment_plans

Revision ID: 00d1856b8216
Revises: c3d67ef01a24
Create Date: 2026-07-12 05:37:43.257903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00d1856b8216'
down_revision = 'c3d67ef01a24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_plans', schema=None) as batch_op:
        batch_op.drop_column('end_date')

    # ### end Alembic commands ###
