"""add saas subscription tracking

Revision ID: 1c3fdcef13ba
Revises: a3f9c2d81e47
Create Date: 2026-06-21 04:16:18.476475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c3fdcef13ba'
down_revision = 'a3f9c2d81e47'
branch_labels = None
depends_on = None


subscription_status_enum = sa.Enum(
    'TRIAL', 'ACTIVE', 'PAST_DUE', 'SUSPENDED', 'CANCELLED', name='subscriptionstatus'
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Postgres needs the enum TYPE created explicitly before a plain ALTER
    # TABLE ADD COLUMN can reference it — unlike op.create_table(), add_column
    # does not auto-create enum types for you.
    subscription_status_enum.create(op.get_bind(), checkfirst=True)

    op.create_table('subscription_tiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('monthly_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_users', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscription_tiers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscription_tiers_code'), ['code'], unique=True)

    op.create_table('subscription_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscription_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscription_payments_clinic_id'), ['clinic_id'], unique=False)

    with op.batch_alter_table('clinics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_tier_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('subscription_status', subscription_status_enum, nullable=False, server_default='TRIAL'))
        batch_op.add_column(sa.Column('trial_ends_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('next_payment_due_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('suspended_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'subscription_tiers', ['subscription_tier_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clinics', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('notes')
        batch_op.drop_column('suspended_at')
        batch_op.drop_column('next_payment_due_at')
        batch_op.drop_column('trial_ends_at')
        batch_op.drop_column('subscription_status')
        batch_op.drop_column('subscription_tier_id')

    with op.batch_alter_table('subscription_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscription_payments_clinic_id'))

    op.drop_table('subscription_payments')
    with op.batch_alter_table('subscription_tiers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscription_tiers_code'))

    op.drop_table('subscription_tiers')
    # ### end Alembic commands ###
    subscription_status_enum.drop(op.get_bind(), checkfirst=True)
