"""add budgets and budget_items tables

Revision ID: 3d0a591ca545
Revises: 00d1856b8216
Create Date: 2026-07-12 17:18:51.102225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d0a591ca545'
down_revision = '00d1856b8216'
branch_labels = None
depends_on = None

# Same fail-closed policy as the rest of the clinic-scoped tables (see
# a3f9c2d81e47_add_row_level_security.py / 22a40bfa3b04_add_payment_plan_installments.py),
# applied here from the start — both new tables get RLS in the same migration
# that creates them, not as a same-day-or-later patch.
POLICY_EXPR = (
    "coalesce(current_setting('app.bypass_rls', true), 'off') = 'on' "
    "OR clinic_id = current_setting('app.current_clinic_id', true)::int"
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('treatment_plan_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('down_payment', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('num_citas', sa.Integer(), nullable=False),
    sa.Column('cost_per_cita', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACCEPTED', 'REJECTED', name='budgetstatus'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('converted_plan_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['converted_plan_id'], ['payment_plans.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['treatment_plan_id'], ['treatment_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budgets_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_budgets_converted_plan_id'), ['converted_plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_budgets_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_budgets_treatment_plan_id'), ['treatment_plan_id'], unique=False)

    op.create_table('budget_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('budget_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('budget_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budget_items_budget_id'), ['budget_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_budget_items_clinic_id'), ['clinic_id'], unique=False)

    # ### end Alembic commands ###

    for table in ("budgets", "budget_items"):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY clinic_isolation ON {table} "
            f"USING ({POLICY_EXPR}) WITH CHECK ({POLICY_EXPR})"
        )


def downgrade():
    for table in ("budget_items", "budgets"):
        op.execute(f"DROP POLICY IF EXISTS clinic_isolation ON {table}")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budget_items_clinic_id'))
        batch_op.drop_index(batch_op.f('ix_budget_items_budget_id'))

    op.drop_table('budget_items')
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budgets_treatment_plan_id'))
        batch_op.drop_index(batch_op.f('ix_budgets_patient_id'))
        batch_op.drop_index(batch_op.f('ix_budgets_converted_plan_id'))
        batch_op.drop_index(batch_op.f('ix_budgets_clinic_id'))

    op.drop_table('budgets')
    # ### end Alembic commands ###
