"""add plan_started_at and plan_expires_at to clinics

Revision ID: 5c4fe2b33646
Revises: 22a40bfa3b04
Create Date: 2026-06-22 22:51:57.165576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c4fe2b33646'
down_revision = '22a40bfa3b04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clinics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('plan_expires_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clinics', schema=None) as batch_op:
        batch_op.drop_column('plan_expires_at')
        batch_op.drop_column('plan_started_at')

    # ### end Alembic commands ###
